### ISSUE TITLE
tcp connection refused on migration image

### ISSUE THREAD

**Issue by ndoniyor** [blnkledger/blnk#22]
Looks like it's trying to connect before the postgres container is ready. Would like to fix myself if possible.

**Comment by jerry-enebeli** [comment]
Hi @ndoniyor,

Yeah, I've noticed that issue too. Sure, if you're able to help figure it out, please feel free to send in a PR. Thank you!

**Comment by struckchure** [comment]
> Looks like it's trying to connect before the postgres container is ready. Would like to fix myself if possible.

Re-ordering the boot order with the `depends_on` in the docker-compose file should fix it
