### ISSUE TITLE
Date not being returned correctly

### ISSUE THREAD

**Issue by peoray** [blnkledger/blnk#34]
**Describe the bug**
When recording a transaction, the `created_at` property has a weird date format, which means an empty date. This should not be the case as it should assume the date and time the request was successful.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
<img width="1101" alt="Screenshot 2024-06-05 at 7 44 33 PM" src="https://github.com/blnkledger/blnk/assets/23735423/aef590e7-f41c-477e-a37e-d4a87764420a">

**Platform (please complete the following information):**

**Additional context**

**Comment by jerry-enebeli** [comment]
Thank you, @peoray. I'll look into this.
